services:
  db:
    image: cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES" ]
      interval: 30s
      timeout: 10s
      retries: 5

  start-db:
    image: nuvo/docker-cqlsh
    environment:
      CQLSH_HOST: db
      CQLSH_PORT: 9042
      CQLVERSION: 3.4.7
    volumes:
      - ./data.cql:/scripts/data.cql
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - start
